"""Update models

Revision ID: 7a65ad6797ec
Revises: 8e60e0905da7
Create Date: 2024-10-28 03:29:07.221921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a65ad6797ec'
down_revision = '8e60e0905da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_episodes_number'), ['number'])

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('occupation', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_column('occupation')
        batch_op.drop_column('name')

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_episodes_number'), type_='unique')
        batch_op.drop_column('number')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
