"""Add fields to Appearance model

Revision ID: 8e60e0905da7
Revises: 5de24ecc04c8
Create Date: 2024-10-28 02:52:42.291256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e60e0905da7'
down_revision = '5de24ecc04c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('episode_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('guest_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_appearances_guest_id_guests'), 'guests', ['guest_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_appearances_episode_id_episodes'), 'episodes', ['episode_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appearances_episode_id_episodes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_appearances_guest_id_guests'), type_='foreignkey')
        batch_op.drop_column('guest_id')
        batch_op.drop_column('episode_id')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
